### ISSUE TITLE
Display:Block causes some problems

### ISSUE THREAD

**Issue by wellitsucks** [Dots-Studio/NeonUI#1]
**Describe the bug**
*{display:block} makes all scripts and styles visible and users cant see the page

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/83873781/150430952-5c90b439-a36a-4dd7-bf8e-cfe0c114250b.png)

**Comment by AlurDesign** [comment]
Thanks for reporting - We've fixed it in NeonUI 0.5.11 :)
